name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get release version from pyproject.toml
        run: |
          awk '/^version =/' pyproject.toml \
            | tr '[:lower:]' '[:upper:]' | tr -d ' "' \
            >> $GITHUB_ENV

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create v${{ env.VERSION }}

      - name: Check the package and run the tests
        run: make check && make test

      - name: Build archive
        shell: bash
        run: make build && echo "WHL_PATH=\"$(ls dist/*)\"" >> $GITHUB_ENV

      - name: Upload the wheel
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload v${{ env.VERSION }} ${{ env.WHL_PATH }}
